package com.temp.chart.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.temp.chart.model.MonthContent;

import com.temp.chart.model.MonthContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig monthContentDaoConfig;

    private final MonthContentDao monthContentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        monthContentDaoConfig = daoConfigMap.get(MonthContentDao.class).clone();
        monthContentDaoConfig.initIdentityScope(type);

        monthContentDao = new MonthContentDao(monthContentDaoConfig, this);

        registerDao(MonthContent.class, monthContentDao);
    }
    
    public void clear() {
        monthContentDaoConfig.clearIdentityScope();
    }

    public MonthContentDao getMonthContentDao() {
        return monthContentDao;
    }

}
