package com.temp.chart.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MONTH_CONTENT".
*/
public class MonthContentDao extends AbstractDao<MonthContent, Long> {

    public static final String TABLENAME = "MONTH_CONTENT";

    /**
     * Properties of entity MonthContent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Month = new Property(1, String.class, "month", false, "MONTH");
        public final static Property Value = new Property(2, float.class, "value", false, "VALUE");
        public final static Property Tag = new Property(3, int.class, "tag", false, "TAG");
    }


    public MonthContentDao(DaoConfig config) {
        super(config);
    }
    
    public MonthContentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MONTH_CONTENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MONTH\" TEXT," + // 1: month
                "\"VALUE\" REAL NOT NULL ," + // 2: value
                "\"TAG\" INTEGER NOT NULL );"); // 3: tag
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MONTH_CONTENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MonthContent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String month = entity.getMonth();
        if (month != null) {
            stmt.bindString(2, month);
        }
        stmt.bindDouble(3, entity.getValue());
        stmt.bindLong(4, entity.getTag());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MonthContent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String month = entity.getMonth();
        if (month != null) {
            stmt.bindString(2, month);
        }
        stmt.bindDouble(3, entity.getValue());
        stmt.bindLong(4, entity.getTag());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MonthContent readEntity(Cursor cursor, int offset) {
        MonthContent entity = new MonthContent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // month
            cursor.getFloat(offset + 2), // value
            cursor.getInt(offset + 3) // tag
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MonthContent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMonth(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setValue(cursor.getFloat(offset + 2));
        entity.setTag(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MonthContent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MonthContent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MonthContent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
